// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_EaXi4OI5SEndI-Phe4FfJ6P7M5MaoA',
    appId: '1:289031542511:web:d654b9d43d11d2f98b6d1a',
    messagingSenderId: '289031542511',
    projectId: 'happy-deals-3f03d',
    authDomain: 'happy-deals-3f03d.firebaseapp.com',
    storageBucket: 'happy-deals-3f03d.appspot.com',
    measurementId: 'G-Y2Q98Z88J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN5p1yVmLO4ulDEgAsxQKiBVum8G1ZIAY',
    appId: '1:289031542511:android:54b88775765ba71a8b6d1a',
    messagingSenderId: '289031542511',
    projectId: 'happy-deals-3f03d',
    storageBucket: 'happy-deals-3f03d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoq96GhNzE5ODbQlGGU3w54C47MaJfw4Y',
    appId: '1:289031542511:ios:75633c50745ea4c48b6d1a',
    messagingSenderId: '289031542511',
    projectId: 'happy-deals-3f03d',
    storageBucket: 'happy-deals-3f03d.appspot.com',
    iosBundleId: 'com.example.happyDealsPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoq96GhNzE5ODbQlGGU3w54C47MaJfw4Y',
    appId: '1:289031542511:ios:75633c50745ea4c48b6d1a',
    messagingSenderId: '289031542511',
    projectId: 'happy-deals-3f03d',
    storageBucket: 'happy-deals-3f03d.appspot.com',
    iosBundleId: 'com.example.happyDealsPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF_EaXi4OI5SEndI-Phe4FfJ6P7M5MaoA',
    appId: '1:289031542511:web:d2b308bcbff053af8b6d1a',
    messagingSenderId: '289031542511',
    projectId: 'happy-deals-3f03d',
    authDomain: 'happy-deals-3f03d.firebaseapp.com',
    storageBucket: 'happy-deals-3f03d.appspot.com',
    measurementId: 'G-RQ17CGJLFT',
  );
}
